version: '3.7'

services:
  app:
    build: .
    container_name: work-anywhere-test
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app # Manda tudo que esta em . (meu projeto) para /home/node/app
      - /home/node/app/node_modules # Preserva node_modules
      - /home/node/app/dist # Preserva dist
    depends_on:
      - pg

  pg:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  migrations:
    build: .
    command: npm run run-migrations
    links:
      - pg
    depends_on:
      - pg
